# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'run_GUI_v9.ui'
#
# Created by: PyQt5 UI code generator 5.6
# notes:
#  - replace the QTextEdit to QPlainTextEdit on the GUI
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 1361, 731))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabs.setFont(font)
        self.tabs.setObjectName("tabs")
        self.genTab = QtWidgets.QWidget()
        self.genTab.setObjectName("genTab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.genTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 9, 241, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_mouseID = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_mouseID.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_mouseID.setContentsMargins(5, 5, 5, 5)
        self.layout_mouseID.setObjectName("layout_mouseID")
        self.line_13 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.layout_mouseID.addWidget(self.line_13)
        self.label_mouseID = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_mouseID.setFont(font)
        self.label_mouseID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_mouseID.setObjectName("label_mouseID")
        self.layout_mouseID.addWidget(self.label_mouseID)
        self.mouseidexp1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mouseidexp1.setFont(font)
        self.mouseidexp1.setObjectName("mouseidexp1")
        self.layout_mouseID.addWidget(self.mouseidexp1)
        self.mouseidexp2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mouseidexp2.setFont(font)
        self.mouseidexp2.setObjectName("mouseidexp2")
        self.layout_mouseID.addWidget(self.mouseidexp2)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.layout_mouseID.addWidget(self.line_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_channels2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_channels2.setObjectName("label_channels2")
        self.gridLayout.addWidget(self.label_channels2, 5, 0, 1, 1)
        self.label_laser1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_laser1.setObjectName("label_laser1")
        self.gridLayout.addWidget(self.label_laser1, 2, 0, 1, 1)
        self.l4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.l4.setObjectName("l4")
        self.gridLayout.addWidget(self.l4, 14, 1, 1, 1)
        self.label_channels3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_channels3.setObjectName("label_channels3")
        self.gridLayout.addWidget(self.label_channels3, 9, 0, 1, 1)
        self.label_laser4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_laser4.setObjectName("label_laser4")
        self.gridLayout.addWidget(self.label_laser4, 14, 0, 1, 1)
        self.label_laser3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_laser3.setObjectName("label_laser3")
        self.gridLayout.addWidget(self.label_laser3, 10, 0, 1, 1)
        self.ch1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ch1.setObjectName("ch1")
        self.gridLayout.addWidget(self.ch1, 1, 1, 1, 1)
        self.label_laser2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_laser2.setObjectName("label_laser2")
        self.gridLayout.addWidget(self.label_laser2, 6, 0, 1, 1)
        self.ch4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ch4.setObjectName("ch4")
        self.gridLayout.addWidget(self.ch4, 13, 1, 1, 1)
        self.label_channels4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_channels4.setObjectName("label_channels4")
        self.gridLayout.addWidget(self.label_channels4, 13, 0, 1, 1)
        self.l3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.l3.setObjectName("l3")
        self.gridLayout.addWidget(self.l3, 10, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 7, 0, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 3, 0, 1, 1)
        self.l1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.l1.setObjectName("l1")
        self.gridLayout.addWidget(self.l1, 2, 1, 1, 1)
        self.ch2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ch2.setObjectName("ch2")
        self.gridLayout.addWidget(self.ch2, 5, 1, 1, 1)
        self.m1chk = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.m1chk.setObjectName("m1chk")
        self.gridLayout.addWidget(self.m1chk, 0, 0, 1, 1)
        self.id1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.id1.setObjectName("id1")
        self.gridLayout.addWidget(self.id1, 0, 1, 1, 1)
        self.id2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.id2.setObjectName("id2")
        self.gridLayout.addWidget(self.id2, 4, 1, 1, 1)
        self.l2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.l2.setObjectName("l2")
        self.gridLayout.addWidget(self.l2, 6, 1, 1, 1)
        self.m4chk = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.m4chk.setObjectName("m4chk")
        self.gridLayout.addWidget(self.m4chk, 12, 0, 1, 1)
        self.m2chk = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.m2chk.setObjectName("m2chk")
        self.gridLayout.addWidget(self.m2chk, 4, 0, 1, 1)
        self.m3chk = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.m3chk.setObjectName("m3chk")
        self.gridLayout.addWidget(self.m3chk, 8, 0, 1, 1)
        self.id3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.id3.setObjectName("id3")
        self.gridLayout.addWidget(self.id3, 8, 1, 1, 1)
        self.id4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.id4.setObjectName("id4")
        self.gridLayout.addWidget(self.id4, 12, 1, 1, 1)
        self.label_channels1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_channels1.setObjectName("label_channels1")
        self.gridLayout.addWidget(self.label_channels1, 1, 0, 1, 1)
        self.ch3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ch3.setObjectName("ch3")
        self.gridLayout.addWidget(self.ch3, 9, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 11, 0, 1, 1)
        self.layout_mouseID.addLayout(self.gridLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.genTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 220, 281, 457))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_parameters = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_parameters.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_parameters.setContentsMargins(5, 5, 5, 5)
        self.layout_parameters.setObjectName("layout_parameters")
        self.line_14 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.layout_parameters.addWidget(self.line_14)
        self.label_parameters = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_parameters.setFont(font)
        self.label_parameters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_parameters.setObjectName("label_parameters")
        self.layout_parameters.addWidget(self.label_parameters)
        self.paramexp1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.paramexp1.setFont(font)
        self.paramexp1.setObjectName("paramexp1")
        self.layout_parameters.addWidget(self.paramexp1)
        self.paramexp2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.paramexp2.setFont(font)
        self.paramexp2.setObjectName("paramexp2")
        self.layout_parameters.addWidget(self.paramexp2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layout_parameters.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.minPG = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.minPG.setMaximum(1000)
        self.minPG.setProperty("value", 15)
        self.minPG.setObjectName("minPG")
        self.gridLayout_2.addWidget(self.minPG, 11, 1, 1, 1)
        self.maxPG = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.maxPG.setMaximum(1000)
        self.maxPG.setProperty("value", 25)
        self.maxPG.setObjectName("maxPG")
        self.gridLayout_2.addWidget(self.maxPG, 12, 1, 1, 1)
        self.lo = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.lo.setMaximum(1000000)
        self.lo.setProperty("value", 95)
        self.lo.setObjectName("lo")
        self.gridLayout_2.addWidget(self.lo, 8, 1, 1, 1)
        self.hi = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.hi.setMaximum(1000000)
        self.hi.setProperty("value", 5)
        self.hi.setObjectName("hi")
        self.gridLayout_2.addWidget(self.hi, 7, 1, 1, 1)
        self.pulsedur = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.pulsedur.setMaximum(10000)
        self.pulsedur.setProperty("value", 120)
        self.pulsedur.setObjectName("pulsedur")
        self.gridLayout_2.addWidget(self.pulsedur, 6, 1, 1, 1)
        self.expdur = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.expdur.setMaximum(48.0)
        self.expdur.setSingleStep(0.01)
        self.expdur.setProperty("value", 5.0)
        self.expdur.setObjectName("expdur")
        self.gridLayout_2.addWidget(self.expdur, 3, 1, 1, 1)
        self.label_sampling_rate = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_sampling_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sampling_rate.setObjectName("label_sampling_rate")
        self.gridLayout_2.addWidget(self.label_sampling_rate, 1, 0, 1, 1)
        self.label_pulse_duration = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_pulse_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pulse_duration.setObjectName("label_pulse_duration")
        self.gridLayout_2.addWidget(self.label_pulse_duration, 6, 0, 1, 1)
        self.label_pulse_settings = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_pulse_settings.setFont(font)
        self.label_pulse_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pulse_settings.setObjectName("label_pulse_settings")
        self.gridLayout_2.addWidget(self.label_pulse_settings, 5, 0, 1, 1)
        self.label_Experiment_Setting = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_Experiment_Setting.setFont(font)
        self.label_Experiment_Setting.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Experiment_Setting.setObjectName("label_Experiment_Setting")
        self.gridLayout_2.addWidget(self.label_Experiment_Setting, 0, 0, 1, 1)
        self.label_maximum_gap = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_maximum_gap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maximum_gap.setObjectName("label_maximum_gap")
        self.gridLayout_2.addWidget(self.label_maximum_gap, 12, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 9, 0, 1, 1)
        self.label_laser2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_laser2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_laser2_2.setObjectName("label_laser2_2")
        self.gridLayout_2.addWidget(self.label_laser2_2, 8, 0, 1, 1)
        self.label_pulse_high = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_pulse_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pulse_high.setObjectName("label_pulse_high")
        self.gridLayout_2.addWidget(self.label_pulse_high, 7, 0, 1, 1)
        self.label_laser1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_laser1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_laser1_2.setObjectName("label_laser1_2")
        self.gridLayout_2.addWidget(self.label_laser1_2, 3, 0, 1, 1)
        self.label_delay = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay.setObjectName("label_delay")
        self.gridLayout_2.addWidget(self.label_delay, 2, 0, 1, 1)
        self.label_open_loop_settings = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_open_loop_settings.setFont(font)
        self.label_open_loop_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_open_loop_settings.setObjectName("label_open_loop_settings")
        self.gridLayout_2.addWidget(self.label_open_loop_settings, 10, 0, 1, 1)
        self.delay = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.delay.setMaximum(3600)
        self.delay.setObjectName("delay")
        self.gridLayout_2.addWidget(self.delay, 2, 1, 1, 1)
        self.sr = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.sr.setMaximum(50000)
        self.sr.setProperty("value", 1000)
        self.sr.setObjectName("sr")
        self.gridLayout_2.addWidget(self.sr, 1, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 4, 0, 1, 1)
        self.label_minimum_gap = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_minimum_gap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_minimum_gap.setObjectName("label_minimum_gap")
        self.gridLayout_2.addWidget(self.label_minimum_gap, 11, 0, 1, 1)
        self.layout_parameters.addLayout(self.gridLayout_2)
        self.line_box1 = QtWidgets.QFrame(self.genTab)
        self.line_box1.setGeometry(QtCore.QRect(570, 120, 20, 191))
        self.line_box1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_box1.setLineWidth(3)
        self.line_box1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_box1.setObjectName("line_box1")
        self.label_box1 = QtWidgets.QLabel(self.genTab)
        self.label_box1.setGeometry(QtCore.QRect(585, 210, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box1.setFont(font)
        self.label_box1.setObjectName("label_box1")
        self.label_box2 = QtWidgets.QLabel(self.genTab)
        self.label_box2.setGeometry(QtCore.QRect(585, 410, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box2.setFont(font)
        self.label_box2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_box2.setObjectName("label_box2")
        self.cam1view = pg.ImageView(self.genTab)
        self.cam1view.ui.histogram.hide()
        self.cam1view.ui.roiBtn.hide()
        self.cam1view.ui.menuBtn.hide()
        self.cam1view.setGeometry(QtCore.QRect(920, 22, 419, 313))
        self.cam1view.setObjectName("cam1view")
        self.cam2view = pg.ImageView(self.genTab)
        self.cam2view.ui.histogram.hide()
        self.cam2view.ui.roiBtn.hide()
        self.cam2view.ui.menuBtn.hide()
        self.cam2view.setGeometry(QtCore.QRect(920, 360, 419, 313))
        self.cam2view.setObjectName("cam2view")
        self.label_box1cam = QtWidgets.QLabel(self.genTab)
        self.label_box1cam.setGeometry(QtCore.QRect(940, 0, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_box1cam.setFont(font)
        self.label_box1cam.setObjectName("label_box1cam")
        self.label_box2cam = QtWidgets.QLabel(self.genTab)
        self.label_box2cam.setGeometry(QtCore.QRect(940, 340, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_box2cam.setFont(font)
        self.label_box2cam.setObjectName("label_box2cam")
        self.commentbox = QtWidgets.QPlainTextEdit(self.genTab)
        self.commentbox.setGeometry(QtCore.QRect(640, 595, 261, 46))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commentbox.setFont(font)
        self.commentbox.setObjectName("commentbox")
        self.label_comments = QtWidgets.QLabel(self.genTab)
        self.label_comments.setGeometry(QtCore.QRect(640, 460, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_comments.setFont(font)
        self.label_comments.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_comments.setObjectName("label_comments")
        self.entercomment = QtWidgets.QPushButton(self.genTab)
        self.entercomment.setGeometry(QtCore.QRect(640, 645, 261, 31))
        self.entercomment.setObjectName("entercomment")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.genTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 281, 208))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_protocol = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_protocol.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_protocol.setContentsMargins(5, 5, 5, 5)
        self.layout_protocol.setObjectName("layout_protocol")
        self.line_12 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.layout_protocol.addWidget(self.line_12)
        self.label_options = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_options.setFont(font)
        self.label_options.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_options.setObjectName("label_options")
        self.layout_protocol.addWidget(self.label_options)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.layout_protocol.addWidget(self.line_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.option_default = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.option_default.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.option_default.setChecked(True)
        self.option_default.setAutoRepeat(False)
        self.option_default.setAutoExclusive(True)
        self.option_default.setObjectName("option_default")
        self.gridLayout_3.addWidget(self.option_default, 0, 0, 1, 1)
        self.option_ol = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.option_ol.setObjectName("option_ol")
        self.gridLayout_3.addWidget(self.option_ol, 1, 0, 1, 1)
        self.option_cl = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.option_cl.setObjectName("option_cl")
        self.gridLayout_3.addWidget(self.option_cl, 2, 0, 1, 1)
        self.option_remdep = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.option_remdep.setObjectName("option_remdep")
        self.gridLayout_3.addWidget(self.option_remdep, 3, 0, 1, 1)
        self.option_nremdep = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.option_nremdep.setObjectName("option_nremdep")
        self.gridLayout_3.addWidget(self.option_nremdep, 4, 0, 1, 1)
        self.layout_protocol.addLayout(self.gridLayout_3)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.genTab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(640, 10, 121, 162))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.layout_mainControl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_mainControl.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_mainControl.setContentsMargins(5, 5, 5, 5)
        self.layout_mainControl.setObjectName("layout_mainControl")
        self.line_15 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.layout_mainControl.addWidget(self.line_15)
        self.label_main_control = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_main_control.setFont(font)
        self.label_main_control.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_main_control.setObjectName("label_main_control")
        self.layout_mainControl.addWidget(self.label_main_control)
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.layout_mainControl.addWidget(self.line_10)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        font = QtGui.QFont() ## added
        font.setPointSize(12) ## added
        self.startbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.startbutton.setObjectName("startbutton")
        self.startbutton.setFont(font) ## added
        self.gridLayout_4.addWidget(self.startbutton, 1, 0, 1, 1)
        self.preview = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.preview.setFont(font) ## added
        self.preview.setObjectName("preview")
        self.gridLayout_4.addWidget(self.preview, 0, 0, 1, 1)
        self.stopbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.stopbutton.setObjectName("stopbutton")
        self.gridLayout_4.addWidget(self.stopbutton, 2, 0, 1, 1)
        self.layout_mainControl.addLayout(self.gridLayout_4)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.genTab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(330, 520, 271, 151))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.layout_connectDevices = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.layout_connectDevices.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_connectDevices.setContentsMargins(5, 5, 5, 5)
        self.layout_connectDevices.setObjectName("layout_connectDevices")
        self.label_connect_devices = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_connect_devices.setFont(font)
        self.label_connect_devices.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_connect_devices.setObjectName("label_connect_devices")
        self.layout_connectDevices.addWidget(self.label_connect_devices)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget_5)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.layout_connectDevices.addWidget(self.line_9)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.connect_c1 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.connect_c1.setObjectName("connect_c1")
        self.gridLayout_5.addWidget(self.connect_c1, 1, 0, 1, 1)
        self.led_cam1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.led_cam1.setText("")
        self.led_cam1.setAlignment(QtCore.Qt.AlignCenter)
        self.led_cam1.setObjectName("led_cam1")
        self.led_cam1.setPixmap(QtGui.QPixmap("led_off.png"))
        self.led_cam1.setScaledContents(True)
        self.gridLayout_5.addWidget(self.led_cam1, 1, 2, 1, 1)
        self.connect_c2 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.connect_c2.setObjectName("connect_c2")
        self.gridLayout_5.addWidget(self.connect_c2, 2, 0, 1, 1)
        self.led_cam2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.led_cam2.setText("")
        self.led_cam2.setAlignment(QtCore.Qt.AlignCenter)
        self.led_cam2.setObjectName("led_cam2")
        self.led_cam2.setPixmap(QtGui.QPixmap("led_off.png"))
        self.led_cam2.setScaledContents(True)
        self.gridLayout_5.addWidget(self.led_cam2, 2, 2, 1, 1)
        self.led_controller = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.led_controller.setText("")
        self.led_controller.setAlignment(QtCore.Qt.AlignCenter)
        self.led_controller.setObjectName("led_controller")
        self.led_controller.setPixmap(QtGui.QPixmap("led_off.png"))
        self.led_controller.setScaledContents(True)
        self.gridLayout_5.addWidget(self.led_controller, 0, 2, 1, 1)
        self.connect_controller = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.connect_controller.setObjectName("connect_controller")
        self.gridLayout_5.addWidget(self.connect_controller, 0, 0, 1, 1)
        self.spacer1 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.spacer1.setText("")
        self.spacer1.setObjectName("spacer1")
        self.gridLayout_5.addWidget(self.spacer1, 0, 1, 1, 1)
        self.layout_connectDevices.addLayout(self.gridLayout_5)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.genTab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(640, 180, 261, 272))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.layout_pulseControl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.layout_pulseControl.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_pulseControl.setContentsMargins(5, 5, 5, 5)
        self.layout_pulseControl.setObjectName("layout_pulseControl")
        self.line_16 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.layout_pulseControl.addWidget(self.line_16)
        self.label_pulse_control = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_pulse_control.setFont(font)
        self.label_pulse_control.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pulse_control.setObjectName("label_pulse_control")
        self.layout_pulseControl.addWidget(self.label_pulse_control)
        self.pulseconexp = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pulseconexp.setFont(font)
        self.pulseconexp.setObjectName("pulseconexp")
        self.layout_pulseControl.addWidget(self.pulseconexp)
        self.line_11 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.layout_pulseControl.addWidget(self.line_11)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_lowC = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_lowC.setObjectName("label_lowC")
        self.gridLayout_8.addWidget(self.label_lowC, 1, 0, 1, 1)
        self.hi_c = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.hi_c.setMaximum(100000)
        self.hi_c.setProperty("value", 5)
        self.hi_c.setObjectName("hi_c")
        self.gridLayout_8.addWidget(self.hi_c, 0, 1, 1, 1)
        self.lo_c = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.lo_c.setMaximum(100000)
        self.lo_c.setProperty("value", 45)
        self.lo_c.setObjectName("lo_c")
        self.gridLayout_8.addWidget(self.lo_c, 1, 1, 1, 1)
        self.label_highC = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_highC.setObjectName("label_highC")
        self.gridLayout_8.addWidget(self.label_highC, 0, 0, 1, 1)
        self.dur_c = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_6)
        self.dur_c.setDecimals(1)
        self.dur_c.setMaximum(1000.0)
        self.dur_c.setSingleStep(0.1)
        self.dur_c.setProperty("value", 1.0)
        self.dur_c.setObjectName("dur_c")
        self.gridLayout_8.addWidget(self.dur_c, 2, 1, 1, 1)
        self.label_dur_c = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_dur_c.setObjectName("label_dur_c")
        self.gridLayout_8.addWidget(self.label_dur_c, 2, 0, 1, 1)
        self.layout_pulseControl.addLayout(self.gridLayout_8)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.continuous = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.continuous.setAutoExclusive(False)
        self.continuous.setObjectName("continuous")
        self.gridLayout_6.addWidget(self.continuous, 0, 0, 1, 1)
        self.c_on = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.c_on.setObjectName("c_on")
        self.gridLayout_6.addWidget(self.c_on, 1, 0, 1, 1)
        self.c_off = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.c_off.setObjectName("c_off")
        self.gridLayout_6.addWidget(self.c_off, 2, 0, 1, 1)
        self.layout_pulseControl.addLayout(self.gridLayout_6)
        self.commentHist = QtWidgets.QPlainTextEdit(self.genTab)
        self.commentHist.setGeometry(QtCore.QRect(640, 500, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commentHist.setFont(font)
        self.commentHist.setUndoRedoEnabled(False)
        self.commentHist.setReadOnly(True)
        self.commentHist.setObjectName("commentHist")
        self.line_box1_2 = QtWidgets.QFrame(self.genTab)
        self.line_box1_2.setGeometry(QtCore.QRect(570, 330, 20, 181))
        self.line_box1_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_box1_2.setLineWidth(3)
        self.line_box1_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_box1_2.setObjectName("line_box1_2")
        self.midline_2 = QtWidgets.QFrame(self.genTab)
        self.midline_2.setGeometry(QtCore.QRect(620, 10, 16, 666))
        self.midline_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.midline_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.midline_2.setObjectName("midline_2")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.genTab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(770, 10, 131, 161))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_timeRemaining = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_timeRemaining.setFont(font)
        self.label_timeRemaining.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timeRemaining.setObjectName("label_timeRemaining")
        self.verticalLayout_4.addWidget(self.label_timeRemaining)
        self.t_rem = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.t_rem.setEnabled(True)
        self.t_rem.setFrameShape(QtWidgets.QFrame.Box)
        self.t_rem.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t_rem.setLineWidth(3)
        self.t_rem.setText("")
        self.t_rem.setAlignment(QtCore.Qt.AlignCenter)
        self.t_rem.setObjectName("t_rem")
        self.verticalLayout_4.addWidget(self.t_rem)
        self.label_nextPulse = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nextPulse.setFont(font)
        self.label_nextPulse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nextPulse.setObjectName("label_nextPulse")
        self.verticalLayout_4.addWidget(self.label_nextPulse)
        self.p_rem = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.p_rem.setFrameShape(QtWidgets.QFrame.Box)
        self.p_rem.setLineWidth(3)
        self.p_rem.setText("")
        self.p_rem.setAlignment(QtCore.Qt.AlignCenter)
        self.p_rem.setObjectName("p_rem")
        self.verticalLayout_4.addWidget(self.p_rem)
        self.tabs.addTab(self.genTab, "")
        self.plotTab = QtWidgets.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.graphicsView = pg.GraphicsLayoutWidget(self.plotTab)
        self.graphicsView.setGeometry(QtCore.QRect(240, 10, 1101, 681))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.plotTab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 217, 569))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_closedloopsettings = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_closedloopsettings.setFont(font)
        self.label_closedloopsettings.setObjectName("label_closedloopsettings")
        self.verticalLayout.addWidget(self.label_closedloopsettings)
        self.label_box1_cl = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_box1_cl.setFont(font)
        self.label_box1_cl.setObjectName("label_box1_cl")
        self.verticalLayout.addWidget(self.label_box1_cl)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_thresholds1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thresholds1.setFont(font)
        self.label_thresholds1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thresholds1.setObjectName("label_thresholds1")
        self.horizontalLayout_10.addWidget(self.label_thresholds1)
        self.label_threshMouse1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_threshMouse1.setFont(font)
        self.label_threshMouse1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_threshMouse1.setObjectName("label_threshMouse1")
        self.horizontalLayout_10.addWidget(self.label_threshMouse1)
        self.label_threshMouse2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_threshMouse2.setFont(font)
        self.label_threshMouse2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_threshMouse2.setObjectName("label_threshMouse2")
        self.horizontalLayout_10.addWidget(self.label_threshMouse2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.line_27 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.verticalLayout.addWidget(self.line_27)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_delta_1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_delta_1.setFont(font)
        self.label_delta_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delta_1.setObjectName("label_delta_1")
        self.horizontalLayout.addWidget(self.label_delta_1)
        self.line_21 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout.addWidget(self.line_21)
        self.threshDelta1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshDelta1.setFont(font)
        self.threshDelta1.setMaximum(999999)
        self.threshDelta1.setSingleStep(100)
        self.threshDelta1.setProperty("value", 0)
        self.threshDelta1.setObjectName("threshDelta1")
        self.horizontalLayout.addWidget(self.threshDelta1)
        self.line_28 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.horizontalLayout.addWidget(self.line_28)
        self.threshDelta2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshDelta2.setFont(font)
        self.threshDelta2.setMaximum(999999)
        self.threshDelta2.setSingleStep(100)
        self.threshDelta2.setObjectName("threshDelta2")
        self.horizontalLayout.addWidget(self.threshDelta2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_updel_1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_updel_1.setFont(font)
        self.label_updel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_updel_1.setObjectName("label_updel_1")
        self.horizontalLayout_2.addWidget(self.label_updel_1)
        self.line_22 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.horizontalLayout_2.addWidget(self.line_22)
        self.threshUDelta1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshUDelta1.setFont(font)
        self.threshUDelta1.setMaximum(999999)
        self.threshUDelta1.setSingleStep(100)
        self.threshUDelta1.setObjectName("threshUDelta1")
        self.horizontalLayout_2.addWidget(self.threshUDelta1)
        self.line_29 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.horizontalLayout_2.addWidget(self.line_29)
        self.threshUDelta2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshUDelta2.setFont(font)
        self.threshUDelta2.setMaximum(999999)
        self.threshUDelta2.setSingleStep(100)
        self.threshUDelta2.setObjectName("threshUDelta2")
        self.horizontalLayout_2.addWidget(self.threshUDelta2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_17 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout.addWidget(self.line_17)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_lodel_1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_lodel_1.setFont(font)
        self.label_lodel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lodel_1.setObjectName("label_lodel_1")
        self.horizontalLayout_7.addWidget(self.label_lodel_1)
        self.line_23 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_7.addWidget(self.line_23)
        self.threshLDelta1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshLDelta1.setFont(font)
        self.threshLDelta1.setMaximum(999999)
        self.threshLDelta1.setSingleStep(100)
        self.threshLDelta1.setObjectName("threshLDelta1")
        self.horizontalLayout_7.addWidget(self.threshLDelta1)
        self.line_30 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.horizontalLayout_7.addWidget(self.line_30)
        self.threshLDelta2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshLDelta2.setFont(font)
        self.threshLDelta2.setMaximum(999999)
        self.threshLDelta2.setSingleStep(100)
        self.threshLDelta2.setObjectName("threshLDelta2")
        self.horizontalLayout_7.addWidget(self.threshLDelta2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_18 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout.addWidget(self.line_18)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_thd_1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thd_1.setFont(font)
        self.label_thd_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thd_1.setObjectName("label_thd_1")
        self.horizontalLayout_6.addWidget(self.label_thd_1)
        self.line_24 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.horizontalLayout_6.addWidget(self.line_24)
        self.threshThd1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThd1.setFont(font)
        self.threshThd1.setMaximum(999999)
        self.threshThd1.setSingleStep(100)
        self.threshThd1.setObjectName("threshThd1")
        self.horizontalLayout_6.addWidget(self.threshThd1)
        self.line_31 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.horizontalLayout_6.addWidget(self.line_31)
        self.threshThd2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThd2.setFont(font)
        self.threshThd2.setMaximum(999999)
        self.threshThd2.setSingleStep(100)
        self.threshThd2.setObjectName("threshThd2")
        self.horizontalLayout_6.addWidget(self.threshThd2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line_19 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout.addWidget(self.line_19)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_thdl_1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thdl_1.setFont(font)
        self.label_thdl_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thdl_1.setObjectName("label_thdl_1")
        self.horizontalLayout_5.addWidget(self.label_thdl_1)
        self.line_25 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout_5.addWidget(self.line_25)
        self.threshThdl1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThdl1.setFont(font)
        self.threshThdl1.setMaximum(999999)
        self.threshThdl1.setSingleStep(100)
        self.threshThdl1.setObjectName("threshThdl1")
        self.horizontalLayout_5.addWidget(self.threshThdl1)
        self.line_32 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.horizontalLayout_5.addWidget(self.line_32)
        self.threshThdl2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThdl2.setFont(font)
        self.threshThdl2.setMaximum(999999)
        self.threshThdl2.setSingleStep(100)
        self.threshThdl2.setObjectName("threshThdl2")
        self.horizontalLayout_5.addWidget(self.threshThdl2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_20 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout.addWidget(self.line_20)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_mu_1 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_mu_1.setFont(font)
        self.label_mu_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mu_1.setObjectName("label_mu_1")
        self.horizontalLayout_3.addWidget(self.label_mu_1)
        self.line_26 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.horizontalLayout_3.addWidget(self.line_26)
        self.threshMu1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshMu1.setFont(font)
        self.threshMu1.setMaximum(999999)
        self.threshMu1.setSingleStep(100)
        self.threshMu1.setObjectName("threshMu1")
        self.horizontalLayout_3.addWidget(self.threshMu1)
        self.line_33 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.horizontalLayout_3.addWidget(self.line_33)
        self.threshMu2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshMu2.setFont(font)
        self.threshMu2.setMaximum(999999)
        self.threshMu2.setSingleStep(100)
        self.threshMu2.setObjectName("threshMu2")
        self.horizontalLayout_3.addWidget(self.threshMu2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_box2_cl = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_box2_cl.setFont(font)
        self.label_box2_cl.setObjectName("label_box2_cl")
        self.verticalLayout_3.addWidget(self.label_box2_cl)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_thresholds2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thresholds2.setFont(font)
        self.label_thresholds2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thresholds2.setObjectName("label_thresholds2")
        self.horizontalLayout_11.addWidget(self.label_thresholds2)
        self.label_threshMouse3 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_threshMouse3.setFont(font)
        self.label_threshMouse3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_threshMouse3.setObjectName("label_threshMouse3")
        self.horizontalLayout_11.addWidget(self.label_threshMouse3)
        self.label_threshMouse4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_threshMouse4.setFont(font)
        self.label_threshMouse4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_threshMouse4.setObjectName("label_threshMouse4")
        self.horizontalLayout_11.addWidget(self.label_threshMouse4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.line_34 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.verticalLayout_3.addWidget(self.line_34)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_delta_2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_delta_2.setFont(font)
        self.label_delta_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delta_2.setObjectName("label_delta_2")
        self.horizontalLayout_12.addWidget(self.label_delta_2)
        self.line_35 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.horizontalLayout_12.addWidget(self.line_35)
        self.threshDelta3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshDelta3.setFont(font)
        self.threshDelta3.setMaximum(999999)
        self.threshDelta3.setSingleStep(100)
        self.threshDelta3.setObjectName("threshDelta3")
        self.horizontalLayout_12.addWidget(self.threshDelta3)
        self.line_36 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.horizontalLayout_12.addWidget(self.line_36)
        self.threshDelta4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshDelta4.setFont(font)
        self.threshDelta4.setMaximum(999999)
        self.threshDelta4.setSingleStep(100)
        self.threshDelta4.setObjectName("threshDelta4")
        self.horizontalLayout_12.addWidget(self.threshDelta4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.line_37 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.verticalLayout_3.addWidget(self.line_37)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_updel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_updel_2.setFont(font)
        self.label_updel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_updel_2.setObjectName("label_updel_2")
        self.horizontalLayout_13.addWidget(self.label_updel_2)
        self.line_38 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.horizontalLayout_13.addWidget(self.line_38)
        self.threshUDelta3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshUDelta3.setFont(font)
        self.threshUDelta3.setMaximum(999999)
        self.threshUDelta3.setSingleStep(100)
        self.threshUDelta3.setObjectName("threshUDelta3")
        self.horizontalLayout_13.addWidget(self.threshUDelta3)
        self.line_39 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.horizontalLayout_13.addWidget(self.line_39)
        self.threshUDelta4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshUDelta4.setFont(font)
        self.threshUDelta4.setMaximum(999999)
        self.threshUDelta4.setSingleStep(100)
        self.threshUDelta4.setObjectName("threshUDelta4")
        self.horizontalLayout_13.addWidget(self.threshUDelta4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.line_40 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.verticalLayout_3.addWidget(self.line_40)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_lodel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_lodel_2.setFont(font)
        self.label_lodel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lodel_2.setObjectName("label_lodel_2")
        self.horizontalLayout_14.addWidget(self.label_lodel_2)
        self.line_41 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.horizontalLayout_14.addWidget(self.line_41)
        self.threshLDelta3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshLDelta3.setFont(font)
        self.threshLDelta3.setMaximum(999999)
        self.threshLDelta3.setSingleStep(100)
        self.threshLDelta3.setObjectName("threshLDelta3")
        self.horizontalLayout_14.addWidget(self.threshLDelta3)
        self.line_42 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.horizontalLayout_14.addWidget(self.line_42)
        self.threshLDelta4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshLDelta4.setFont(font)
        self.threshLDelta4.setMaximum(999999)
        self.threshLDelta4.setSingleStep(100)
        self.threshLDelta4.setObjectName("threshLDelta4")
        self.horizontalLayout_14.addWidget(self.threshLDelta4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.line_43 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.verticalLayout_3.addWidget(self.line_43)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_thd_2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thd_2.setFont(font)
        self.label_thd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thd_2.setObjectName("label_thd_2")
        self.horizontalLayout_15.addWidget(self.label_thd_2)
        self.line_44 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.horizontalLayout_15.addWidget(self.line_44)
        self.threshThd3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThd3.setFont(font)
        self.threshThd3.setMaximum(999999)
        self.threshThd3.setSingleStep(100)
        self.threshThd3.setObjectName("threshThd3")
        self.horizontalLayout_15.addWidget(self.threshThd3)
        self.line_45 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.horizontalLayout_15.addWidget(self.line_45)
        self.threshThd4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThd4.setFont(font)
        self.threshThd4.setMaximum(999999)
        self.threshThd4.setSingleStep(100)
        self.threshThd4.setObjectName("threshThd4")
        self.horizontalLayout_15.addWidget(self.threshThd4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.line_46 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.verticalLayout_3.addWidget(self.line_46)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_thdl_2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_thdl_2.setFont(font)
        self.label_thdl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thdl_2.setObjectName("label_thdl_2")
        self.horizontalLayout_16.addWidget(self.label_thdl_2)
        self.line_47 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.horizontalLayout_16.addWidget(self.line_47)
        self.threshThdl3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThdl3.setFont(font)
        self.threshThdl3.setMaximum(999999)
        self.threshThdl3.setSingleStep(100)
        self.threshThdl3.setObjectName("threshThdl3")
        self.horizontalLayout_16.addWidget(self.threshThdl3)
        self.line_48 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.horizontalLayout_16.addWidget(self.line_48)
        self.threshThdl4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshThdl4.setFont(font)
        self.threshThdl4.setMaximum(999999)
        self.threshThdl4.setSingleStep(100)
        self.threshThdl4.setObjectName("threshThdl4")
        self.horizontalLayout_16.addWidget(self.threshThdl4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.line_49 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.verticalLayout_3.addWidget(self.line_49)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_mu_2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_mu_2.setFont(font)
        self.label_mu_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mu_2.setObjectName("label_mu_2")
        self.horizontalLayout_17.addWidget(self.label_mu_2)
        self.line_50 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.horizontalLayout_17.addWidget(self.line_50)
        self.threshMu3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshMu3.setFont(font)
        self.threshMu3.setMaximum(999999)
        self.threshMu3.setSingleStep(100)
        self.threshMu3.setObjectName("threshMu3")
        self.horizontalLayout_17.addWidget(self.threshMu3)
        self.line_51 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.horizontalLayout_17.addWidget(self.line_51)
        self.threshMu4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threshMu4.setFont(font)
        self.threshMu4.setMaximum(999999)
        self.threshMu4.setSingleStep(100)
        self.threshMu4.setObjectName("threshMu4")
        self.horizontalLayout_17.addWidget(self.threshMu4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.tabs.addTab(self.plotTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.actionLoad_Settings = QtWidgets.QAction(MainWindow)
        self.actionLoad_Settings.setObjectName("actionLoad_Settings")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionSave_Settings)
        self.menuFile.addAction(self.actionLoad_Settings)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabs, self.option_default)
        MainWindow.setTabOrder(self.option_default, self.option_ol)
        MainWindow.setTabOrder(self.option_ol, self.option_cl)
        MainWindow.setTabOrder(self.option_cl, self.option_remdep)
        MainWindow.setTabOrder(self.option_remdep, self.option_nremdep)
        MainWindow.setTabOrder(self.option_nremdep, self.sr)
        MainWindow.setTabOrder(self.sr, self.delay)
        MainWindow.setTabOrder(self.delay, self.expdur)
        MainWindow.setTabOrder(self.expdur, self.pulsedur)
        MainWindow.setTabOrder(self.pulsedur, self.hi)
        MainWindow.setTabOrder(self.hi, self.lo)
        MainWindow.setTabOrder(self.lo, self.minPG)
        MainWindow.setTabOrder(self.minPG, self.maxPG)
        MainWindow.setTabOrder(self.maxPG, self.m1chk)
        MainWindow.setTabOrder(self.m1chk, self.id1)
        MainWindow.setTabOrder(self.id1, self.ch1)
        MainWindow.setTabOrder(self.ch1, self.l1)
        MainWindow.setTabOrder(self.l1, self.m2chk)
        MainWindow.setTabOrder(self.m2chk, self.id2)
        MainWindow.setTabOrder(self.id2, self.ch2)
        MainWindow.setTabOrder(self.ch2, self.l2)
        MainWindow.setTabOrder(self.l2, self.m3chk)
        MainWindow.setTabOrder(self.m3chk, self.id3)
        MainWindow.setTabOrder(self.id3, self.ch3)
        MainWindow.setTabOrder(self.ch3, self.l3)
        MainWindow.setTabOrder(self.l3, self.m4chk)
        MainWindow.setTabOrder(self.m4chk, self.id4)
        MainWindow.setTabOrder(self.id4, self.ch4)
        MainWindow.setTabOrder(self.ch4, self.l4)
        MainWindow.setTabOrder(self.l4, self.connect_controller)
        MainWindow.setTabOrder(self.connect_controller, self.connect_c1)
        MainWindow.setTabOrder(self.connect_c1, self.connect_c2)
        MainWindow.setTabOrder(self.connect_c2, self.preview)
        MainWindow.setTabOrder(self.preview, self.startbutton)
        MainWindow.setTabOrder(self.startbutton, self.stopbutton)
        MainWindow.setTabOrder(self.stopbutton, self.hi_c)
        MainWindow.setTabOrder(self.hi_c, self.lo_c)
        MainWindow.setTabOrder(self.lo_c, self.dur_c)
        MainWindow.setTabOrder(self.dur_c, self.continuous)
        MainWindow.setTabOrder(self.continuous, self.c_on)
        MainWindow.setTabOrder(self.c_on, self.c_off)
        MainWindow.setTabOrder(self.c_off, self.commentHist)
        MainWindow.setTabOrder(self.commentHist, self.commentbox)
        MainWindow.setTabOrder(self.commentbox, self.entercomment)
        MainWindow.setTabOrder(self.entercomment, self.cam1view)
        MainWindow.setTabOrder(self.cam1view, self.cam2view)
        MainWindow.setTabOrder(self.cam2view, self.threshDelta1)
        MainWindow.setTabOrder(self.threshDelta1, self.threshDelta2)
        MainWindow.setTabOrder(self.threshDelta2, self.threshUDelta1)
        MainWindow.setTabOrder(self.threshUDelta1, self.threshUDelta2)
        MainWindow.setTabOrder(self.threshUDelta2, self.threshLDelta1)
        MainWindow.setTabOrder(self.threshLDelta1, self.threshLDelta2)
        MainWindow.setTabOrder(self.threshLDelta2, self.threshThd1)
        MainWindow.setTabOrder(self.threshThd1, self.threshThd2)
        MainWindow.setTabOrder(self.threshThd2, self.threshThdl1)
        MainWindow.setTabOrder(self.threshThdl1, self.threshThdl2)
        MainWindow.setTabOrder(self.threshThdl2, self.threshMu1)
        MainWindow.setTabOrder(self.threshMu1, self.threshMu2)
        MainWindow.setTabOrder(self.threshMu2, self.threshDelta3)
        MainWindow.setTabOrder(self.threshDelta3, self.threshDelta4)
        MainWindow.setTabOrder(self.threshDelta4, self.threshUDelta3)
        MainWindow.setTabOrder(self.threshUDelta3, self.threshUDelta4)
        MainWindow.setTabOrder(self.threshUDelta4, self.threshLDelta3)
        MainWindow.setTabOrder(self.threshLDelta3, self.threshLDelta4)
        MainWindow.setTabOrder(self.threshLDelta4, self.threshThd3)
        MainWindow.setTabOrder(self.threshThd3, self.threshThd4)
        MainWindow.setTabOrder(self.threshThd4, self.threshThdl3)
        MainWindow.setTabOrder(self.threshThdl3, self.threshThdl4)
        MainWindow.setTabOrder(self.threshThdl4, self.threshMu3)
        MainWindow.setTabOrder(self.threshMu3, self.threshMu4)
        MainWindow.setTabOrder(self.threshMu4, self.graphicsView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sleep Recording"))
        self.label_mouseID.setText(_translate("MainWindow", "Mouse ID"))
        self.mouseidexp1.setText(_translate("MainWindow", "Write mouse ID and its channels / laser ID"))
        self.mouseidexp2.setText(_translate("MainWindow", "(i.e. meEM for channels, B3_4.56bR for lasers)"))
        self.label_channels2.setText(_translate("MainWindow", "Channels"))
        self.label_laser1.setText(_translate("MainWindow", "Laser"))
        self.label_channels3.setText(_translate("MainWindow", "Channels"))
        self.label_laser4.setText(_translate("MainWindow", "Laser"))
        self.label_laser3.setText(_translate("MainWindow", "Laser"))
        self.label_laser2.setText(_translate("MainWindow", "Laser"))
        self.label_channels4.setText(_translate("MainWindow", "Channels"))
        self.m1chk.setText(_translate("MainWindow", "Mouse 1"))
        self.m4chk.setText(_translate("MainWindow", "Mouse 4"))
        self.m2chk.setText(_translate("MainWindow", "Mouse 2"))
        self.m3chk.setText(_translate("MainWindow", "Mouse 3"))
        self.label_channels1.setText(_translate("MainWindow", "Channels"))
        self.label_parameters.setText(_translate("MainWindow", "Parameters"))
        self.paramexp1.setText(_translate("MainWindow", "Choose the experiment durations."))
        self.paramexp2.setText(_translate("MainWindow", "Setting the delay will start recording after the delay."))
        self.label_sampling_rate.setText(_translate("MainWindow", "Sampling Rate"))
        self.label_pulse_duration.setText(_translate("MainWindow", "Pulse Duration (sec)"))
        self.label_pulse_settings.setText(_translate("MainWindow", "Pulse Settings"))
        self.label_Experiment_Setting.setText(_translate("MainWindow", "Experiment Setting"))
        self.label_maximum_gap.setText(_translate("MainWindow", "Maximum Gap (min)"))
        self.label_laser2_2.setText(_translate("MainWindow", "Pulse Low (ms)"))
        self.label_pulse_high.setText(_translate("MainWindow", "Pulse High (ms)"))
        self.label_laser1_2.setText(_translate("MainWindow", "Experiment Dur. (hr)"))
        self.label_delay.setText(_translate("MainWindow", "Delay (min)"))
        self.label_open_loop_settings.setText(_translate("MainWindow", "Open Loop Settings"))
        self.label_minimum_gap.setText(_translate("MainWindow", "Minimum Gap (min)"))
        self.label_box1.setText(_translate("MainWindow", "Box 1"))
        self.label_box2.setText(_translate("MainWindow", "Box2"))
        self.label_box1cam.setText(_translate("MainWindow", "Box 1 Cam"))
        self.label_box2cam.setText(_translate("MainWindow", "Box 2 Cam"))
        self.commentbox.setPlaceholderText(_translate("MainWindow", "Enter Comments Here"))
        self.label_comments.setText(_translate("MainWindow", "Comments"))
        self.entercomment.setText(_translate("MainWindow", "Submit"))
        self.label_options.setText(_translate("MainWindow", "Protocol"))
        self.option_default.setText(_translate("MainWindow", "Default Recording"))
        self.option_ol.setText(_translate("MainWindow", "Open Loop (OL)"))
        self.option_cl.setText(_translate("MainWindow", "Closed Loop (CL)"))
        self.option_remdep.setText(_translate("MainWindow", "REM Deprivation"))
        self.option_nremdep.setText(_translate("MainWindow", "NREM Deprivation"))
        self.label_main_control.setText(_translate("MainWindow", "Control"))
        self.startbutton.setText(_translate("MainWindow", "Start"))
        self.preview.setText(_translate("MainWindow", "Preview"))
        self.stopbutton.setText(_translate("MainWindow", "Stop"))
        self.t_rem.setText(_translate("MainWindow", "IDLE"))
        self.p_rem.setText(_translate("MainWindow", "IDLE"))
        self.label_connect_devices.setText(_translate("MainWindow", "Connect Devices"))
        self.connect_c1.setText(_translate("MainWindow", "Camera 1"))
        self.connect_c2.setText(_translate("MainWindow", "Camera 2"))
        self.connect_controller.setText(_translate("MainWindow", "Microcontroller"))
        self.label_pulse_control.setText(_translate("MainWindow", "Pulse Control"))
        self.pulseconexp.setText(_translate("MainWindow", "For use during preview and troubleshooting."))
        self.label_lowC.setText(_translate("MainWindow", "Low (ms)"))
        self.label_highC.setText(_translate("MainWindow", "High (ms)"))
        self.label_dur_c.setText(_translate("MainWindow", "Duration (sec)"))
        self.continuous.setText(_translate("MainWindow", "Continuous?"))
        self.c_on.setText(_translate("MainWindow", "On"))
        self.c_off.setText(_translate("MainWindow", "Off"))
        self.commentHist.appendPlainText(_translate("MainWindow", "Comment history:"))
        self.label_timeRemaining.setText(_translate("MainWindow", "Time Remaining:"))
        self.label_nextPulse.setText(_translate("MainWindow", "Next Pulse:"))
        self.tabs.setTabText(self.tabs.indexOf(self.genTab), _translate("MainWindow", "General"))
        self.label_closedloopsettings.setText(_translate("MainWindow", "Closed Loop Settings"))
        self.label_box1_cl.setText(_translate("MainWindow", "Box 1"))
        self.label_thresholds1.setText(_translate("MainWindow", "Thresholds"))
        self.label_threshMouse1.setText(_translate("MainWindow", "Mouse 1"))
        self.label_threshMouse2.setText(_translate("MainWindow", "Mouse 2"))
        self.label_delta_1.setText(_translate("MainWindow", "Delta"))
        self.label_updel_1.setText(_translate("MainWindow", "Upper Delta"))
        self.label_lodel_1.setText(_translate("MainWindow", "Lower Delta"))
        self.label_thd_1.setText(_translate("MainWindow", "Upper th/d"))
        self.label_thdl_1.setText(_translate("MainWindow", "Lower th/d"))
        self.label_mu_1.setText(_translate("MainWindow", "Mu"))
        self.label_box2_cl.setText(_translate("MainWindow", "Box 2"))
        self.label_thresholds2.setText(_translate("MainWindow", "Thresholds"))
        self.label_threshMouse3.setText(_translate("MainWindow", "Mouse 3"))
        self.label_threshMouse4.setText(_translate("MainWindow", "Mouse 4"))
        self.label_delta_2.setText(_translate("MainWindow", "Delta"))
        self.label_updel_2.setText(_translate("MainWindow", "Upper Delta"))
        self.label_lodel_2.setText(_translate("MainWindow", "Lower Delta"))
        self.label_thd_2.setText(_translate("MainWindow", "Upper th/d"))
        self.label_thdl_2.setText(_translate("MainWindow", "Lower th/d"))
        self.label_mu_2.setText(_translate("MainWindow", "Mu"))
        self.tabs.setTabText(self.tabs.indexOf(self.plotTab), _translate("MainWindow", "Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_Settings.setText(_translate("MainWindow", "Save Settings"))
        self.actionLoad_Settings.setText(_translate("MainWindow", "Load Settings"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())